let planets = {
  letters: [
    // First ring
    {
      letter: "C",
      radius: FIRST_RING_RADIUS,
      angle: 0,
      color: FIRST_RING_COLOR,
      ring: "inner",
    },
    {
      letter: "T",
      radius: FIRST_RING_RADIUS,
      angle: 90,
      color: FIRST_RING_COLOR,
      ring: "inner",
    },
    {
      letter: "S",
      radius: FIRST_RING_RADIUS,
      angle: 180,
      color: FIRST_RING_COLOR,
      ring: "inner",
    },
    {
      letter: "N",
      radius: FIRST_RING_RADIUS,
      angle: 270,
      color: FIRST_RING_COLOR,
      ring: "inner",
    },

    // Second ring
    {
      letter: "A",
      radius: SECOND_RING_RADIUS,
      angle: 0,
      color: SECOND_RING_COLOR,
      ring: "middle",
    },
    {
      letter: "S",
      radius: SECOND_RING_RADIUS,
      angle: 150,
      color: SECOND_RING_COLOR,
      ring: "middle",
    },
    {
      letter: "H",
      radius: SECOND_RING_RADIUS,
      angle: 180,
      color: SECOND_RING_COLOR,
      ring: "middle",
    },
    {
      letter: "A",
      radius: SECOND_RING_RADIUS,
      angle: 270,
      color: SECOND_RING_COLOR,
      ring: "middle",
    },

    // Third ring
    {
      letter: "P",
      radius: THIRD_RING_RADIUS,
      angle: 0,
      color: THIRD_RING_COLOR,
      ring: "outer",
    },
    {
      letter: "T",
      radius: THIRD_RING_RADIUS,
      angle: 150,
      color: THIRD_RING_COLOR,
      ring: "outer",
    },
    {
      letter: "I",
      radius: THIRD_RING_RADIUS,
      angle: 180,
      color: THIRD_RING_COLOR,
      ring: "outer",
    },
    {
      letter: "L",
      radius: THIRD_RING_RADIUS,
      angle: 270,
      color: THIRD_RING_COLOR,
      ring: "outer",
    },
    {
      letter: "S",
      radius: THIRD_RING_RADIUS,
      angle: 300,
      color: THIRD_RING_COLOR,
      ring: "outer",
    },

    // Fourth ring
    {
      letter: "S",
      radius: FOURTH_RING_RADIUS,
      angle: 0,
      color: FOURTH_RING_COLOR,
      ring: "fourth",
    },
    {
      letter: "A",
      radius: FOURTH_RING_RADIUS,
      angle: 150,
      color: FOURTH_RING_COLOR,
      ring: "fourth",
    },
    {
      letter: "P",
      radius: FOURTH_RING_RADIUS,
      angle: 180,
      color: FOURTH_RING_COLOR,
      ring: "fourth",
    },
    {
      letter: "P",
      radius: FOURTH_RING_RADIUS,
      angle: 270,
      color: FOURTH_RING_COLOR,
      ring: "fourth",
    },
    {
      letter: "A",
      radius: FOURTH_RING_RADIUS,
      angle: 300,
      color: FOURTH_RING_COLOR,
      ring: "fourth",
    },

    // Fifth ring
    {
      letter: "R",
      radius: FIFTH_RING_RADIUS,
      angle: 150,
      color: FIFTH_RING_COLOR,
      ring: "fifth",
    },
    {
      letter: "G",
      radius: FIFTH_RING_RADIUS,
      angle: 300,
      color: FIFTH_RING_COLOR,
      ring: "fifth",
    },
  ],
  rings: {
    inner: {
      position: 0,
      targetPosition: 0,
      radius: FIRST_RING_RADIUS,
      color: FIRST_RING_COLOR,
    },
    middle: {
      position: 0,
      targetPosition: 0,
      radius: SECOND_RING_RADIUS,
      color: SECOND_RING_COLOR,
    },
    outer: {
      position: 0,
      targetPosition: 0,
      radius: THIRD_RING_RADIUS,
      color: THIRD_RING_COLOR,
    },
    fourth: {
      position: 0,
      targetPosition: 0,
      radius: FOURTH_RING_RADIUS,
      color: FOURTH_RING_COLOR,
    },
    fifth: {
      position: 0,
      targetPosition: 0,
      radius: FIFTH_RING_RADIUS,
      color: FIFTH_RING_COLOR,
    },
  },
  foundWords: new Set(),
  score: 0,
  autoCheck: false,
  dragState: null,
  selectedRing: null,
  center: { x: 300, y: 300 },
  sun: { letter: "E", radius: 20, color: "#ffdd44" },
};
let flowers = {
  letters: [
    // First ring
    {
      letter: "F",
      radius: FIRST_RING_RADIUS,
      angle: 0,
      color: FIRST_RING_COLOR,
      ring: "inner",
    },
    {
      letter: "A",
      radius: FIRST_RING_RADIUS,
      angle: 60,
      color: FIRST_RING_COLOR,
      ring: "inner",
    },
    {
      letter: "I",
      radius: FIRST_RING_RADIUS,
      angle: 120,
      color: FIRST_RING_COLOR,
      ring: "inner",
    },
    {
      letter: "O",
      radius: FIRST_RING_RADIUS,
      angle: 180,
      color: FIRST_RING_COLOR,
      ring: "inner",
    },
    {
      letter: "I",
      radius: FIRST_RING_RADIUS,
      angle: 240,
      color: FIRST_RING_COLOR,
      ring: "inner",
    },
    {
      letter: "U",
      radius: FIRST_RING_RADIUS,
      angle: 300,
      color: FIRST_RING_COLOR,
      ring: "inner",
    },

    // Second ring
    {
      letter: "S",
      radius: SECOND_RING_RADIUS,
      angle: 30,
      color: SECOND_RING_COLOR,
      ring: "middle",
    },
    {
      letter: "C",
      radius: SECOND_RING_RADIUS,
      angle: 60,
      color: SECOND_RING_COLOR,
      ring: "middle",
    },
    {
      letter: "R",
      radius: SECOND_RING_RADIUS,
      angle: 90,
      color: SECOND_RING_COLOR,
      ring: "middle",
    },
    {
      letter: "W",
      radius: SECOND_RING_RADIUS,
      angle: 180,
      color: SECOND_RING_COLOR,
      ring: "middle",
    },
    {
      letter: "L",
      radius: SECOND_RING_RADIUS,
      angle: 210,
      color: SECOND_RING_COLOR,
      ring: "middle",
    },
    {
      letter: "L",
      radius: SECOND_RING_RADIUS,
      angle: 240,
      color: SECOND_RING_COLOR,
      ring: "middle",
    },
    {
      letter: "T",
      radius: SECOND_RING_RADIUS,
      angle: 300,
      color: SECOND_RING_COLOR,
      ring: "middle",
    },

    // Third ring
    {
      letter: "I",
      radius: THIRD_RING_RADIUS,
      angle: 30,
      color: THIRD_RING_COLOR,
      ring: "outer",
    },
    {
      letter: "O",
      radius: THIRD_RING_RADIUS,
      angle: 90,
      color: THIRD_RING_COLOR,
      ring: "outer",
    },
    {
      letter: "E",
      radius: THIRD_RING_RADIUS,
      angle: 180,
      color: THIRD_RING_COLOR,
      ring: "outer",
    },
    {
      letter: "I",
      radius: THIRD_RING_RADIUS,
      angle: 210,
      color: THIRD_RING_COLOR,
      ring: "outer",
    },

    // Fourth ring
    {
      letter: "R",
      radius: FOURTH_RING_RADIUS,
      angle: 30,
      color: FOURTH_RING_COLOR,
      ring: "fourth",
    },
    {
      letter: "S",
      radius: FOURTH_RING_RADIUS,
      angle: 90,
      color: FOURTH_RING_COLOR,
      ring: "fourth",
    },
    {
      letter: "R",
      radius: FOURTH_RING_RADIUS,
      angle: 180,
      color: FOURTH_RING_COLOR,
      ring: "fourth",
    },
    {
      letter: "L",
      radius: FOURTH_RING_RADIUS,
      angle: 210,
      color: FOURTH_RING_COLOR,
      ring: "fourth",
    },

    // Fifth ring
    {
      letter: "I",
      radius: FIFTH_RING_RADIUS,
      angle: 30,
      color: FIFTH_RING_COLOR,
      ring: "fifth",
    },
    {
      letter: "E",
      radius: FIFTH_RING_RADIUS,
      angle: 90,
      color: FIFTH_RING_COLOR,
      ring: "fifth",
    },
    {
      letter: "Y",
      radius: FIFTH_RING_RADIUS,
      angle: 210,
      color: FIFTH_RING_COLOR,
      ring: "fifth",
    },
  ],
  rings: {
    inner: {
      position: 0,
      targetPosition: 0,
      radius: FIRST_RING_RADIUS,
      color: FIRST_RING_COLOR,
    },
    middle: {
      position: 0,
      targetPosition: 0,
      radius: SECOND_RING_RADIUS,
      color: SECOND_RING_COLOR,
    },
    outer: {
      position: 0,
      targetPosition: 0,
      radius: THIRD_RING_RADIUS,
      color: THIRD_RING_COLOR,
    },
    fourth: {
      position: 0,
      targetPosition: 0,
      radius: FOURTH_RING_RADIUS,
      color: FOURTH_RING_COLOR,
    },
    fifth: {
      position: 0,
      targetPosition: 0,
      radius: FIFTH_RING_RADIUS,
      color: FIFTH_RING_COLOR,
    },
  },
  foundWords: new Set(),
  score: 0,
  autoCheck: false,
  dragState: null,
  selectedRing: null,
  center: { x: 300, y: 300 },
  sun: { letter: "L", radius: 20, color: "#ffdd44" },
};
